version: '3.9'
services:
    frontend:
        container_name: react-component-lab
        build: .
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        ports:
            - 3080:3080
        command: yarn dev
